<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <NoBuild>true</NoBuild>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <PackageVersion Condition="'$(PackageVersion)' == ''">0.0.0-local</PackageVersion>
  </PropertyGroup>

  <PropertyGroup>
    <NuspecFile>McProtoNet.Native.nuspec</NuspecFile>
    <NuspecProperties>PackageVersion=$(PackageVersion)</NuspecProperties>
    <NuspecBasePath>package-contents</NuspecBasePath>
  </PropertyGroup>
</Project>
